# Generated by Django 5.0.6 on 2026-07-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_clases_course_classes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="description",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="Descripcion"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="location",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="Ciudad"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                blank=True, default="", max_length=15, verbose_name="Telefono"
            ),
        ),
    ]
