# Generated by Django 5.0.6 on 2026-07-29 16:40

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_profile_description_alter_profile_location_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registration",
            options={
                "verbose_name": "Inscripción",
                "verbose_name_plural": "Inscripciones",
            },
        ),
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.localdate, verbose_name="Fecha"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="classes",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Clases",
            ),
        ),
        migrations.AlterField(
            model_name="mark",
            name="average",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("10")),
                ],
                verbose_name="Promedio",
            ),
        ),
        migrations.AlterField(
            model_name="mark",
            name="mark_1",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="Nota 1",
            ),
        ),
        migrations.AlterField(
            model_name="mark",
            name="mark_2",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="Nota 2",
            ),
        ),
        migrations.AlterField(
            model_name="mark",
            name="mark_3",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="Nota 3",
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="price",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Precio",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendance",
            constraint=models.UniqueConstraint(
                fields=("course", "student", "date"),
                name="unique_attendance_course_student_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.CheckConstraint(
                check=models.Q(("classes__gt", 0)), name="course_classes_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="mark",
            constraint=models.UniqueConstraint(
                fields=("course", "student"), name="unique_mark_course_student"
            ),
        ),
        migrations.AddConstraint(
            model_name="mark",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("mark_1__isnull", True),
                    ("mark_1__range", (0, 10)),
                    _connector="OR",
                ),
                name="mark_1_between_0_and_10",
            ),
        ),
        migrations.AddConstraint(
            model_name="mark",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("mark_2__isnull", True),
                    ("mark_2__range", (0, 10)),
                    _connector="OR",
                ),
                name="mark_2_between_0_and_10",
            ),
        ),
        migrations.AddConstraint(
            model_name="mark",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("mark_3__isnull", True),
                    ("mark_3__range", (0, 10)),
                    _connector="OR",
                ),
                name="mark_3_between_0_and_10",
            ),
        ),
        migrations.AddConstraint(
            model_name="offer",
            constraint=models.CheckConstraint(
                check=models.Q(("price__gte", 0)), name="offer_price_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="registration",
            constraint=models.UniqueConstraint(
                fields=("course", "student"), name="unique_registration_course_student"
            ),
        ),
    ]
