# Generated by Django 5.0.6 on 2026-07-29 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_attendance_present"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="mark",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"groups__name": "estudiante"},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Estudiante",
            ),
        ),
    ]
