# Generated by Django 5.0.6 on 2026-07-29 18:00

import api.validators
import django.core.validators
from django.db import migrations, models


def clear_missing_default_profile_image(apps, schema_editor):
    """Convierte la referencia histórica inexistente en una imagen ausente."""
    Profile = apps.get_model("api", "Profile")
    Profile.objects.filter(image="defaultUser.png").update(image="")


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_mark_student"),
    ]

    operations = [
        migrations.RunPython(
            clear_missing_default_profile_image,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="announcement",
            name="detail",
            field=models.FileField(
                upload_to=api.validators.announcement_upload_to,
                validators=[
                    api.validators.FileSizeValidator(10485760),
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=("jpg", "jpeg", "png", "webp", "pdf")
                    ),
                    api.validators.ContentTypeValidator(
                        ("image/jpeg", "image/png", "image/webp", "application/pdf")
                    ),
                ],
                verbose_name="Detalle",
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="doc",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=api.validators.content_document_upload_to,
                validators=[
                    api.validators.FileSizeValidator(10485760),
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=("pdf", "doc", "docx", "odt", "txt")
                    ),
                    api.validators.ContentTypeValidator(
                        (
                            "application/pdf",
                            "application/msword",
                            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                            "application/vnd.oasis.opendocument.text",
                            "text/plain",
                        )
                    ),
                ],
                verbose_name="Material escrito",
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="img",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=api.validators.content_image_upload_to,
                validators=[
                    api.validators.FileSizeValidator(5242880),
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=("jpg", "jpeg", "png", "webp")
                    ),
                    api.validators.ContentTypeValidator(
                        ("image/jpeg", "image/png", "image/webp")
                    ),
                ],
                verbose_name="Material grafico",
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="videos",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=api.validators.content_video_upload_to,
                validators=[
                    api.validators.FileSizeValidator(52428800),
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=("mp4", "webm", "ogv")
                    ),
                    api.validators.ContentTypeValidator(
                        ("video/mp4", "video/webm", "video/ogg")
                    ),
                ],
                verbose_name="Material de video",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="cv",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=api.validators.profile_cv_upload_to,
                validators=[
                    api.validators.FileSizeValidator(5242880),
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=("pdf", "doc", "docx")
                    ),
                    api.validators.ContentTypeValidator(
                        (
                            "application/pdf",
                            "application/msword",
                            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                        )
                    ),
                ],
                verbose_name="CV",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=api.validators.profile_image_upload_to,
                validators=[
                    api.validators.FileSizeValidator(5242880),
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=("jpg", "jpeg", "png", "webp")
                    ),
                    api.validators.ContentTypeValidator(
                        ("image/jpeg", "image/png", "image/webp")
                    ),
                ],
                verbose_name="Imagen",
            ),
        ),
    ]
