# Generated by Django 5.0.6 on 2026-07-30 07:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def migrate_course_data(apps, schema_editor):
    Category = apps.get_model("api", "CourseCategory")
    Course = apps.get_model("api", "Course")
    Lesson = apps.get_model("api", "CourseLesson")
    names = ("Manipulación de alimentos", "Seguridad alimentaria", "Nutrición", "Cocina", "Sala", "Bar", "Gestión hostelera", "Alérgenos")
    categories = [Category.objects.get_or_create(name=name)[0] for name in names]
    status_map = {"i": "publicado", "d": "desarrollo", "f": "finalizado"}
    for course in Course.objects.all():
        course.category = categories[0]
        course.modality = "presencial"
        course.duration_hours = course.classes
        course.start_date = course.end_date = __import__("datetime").date.today()
        course.capacity = 1
        course.location = "Pendiente de actualizar"
        course.price = 0
        course.objectives = course.detail
        course.requirements = "Sin requisitos"
        course.status = status_map.get(course.status, "borrador")
        course.save()
        if course.legacy_content_id:
            Lesson.objects.create(course=course, content_id=course.legacy_content_id, order=1)



class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_announcement_detail_alter_content_doc_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Activa")),
            ],
            options={
                "verbose_name": "Categoría de curso",
                "verbose_name_plural": "Categorías de curso",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="CourseLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Orden",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lección de curso",
                "verbose_name_plural": "Lecciones de curso",
                "ordering": ("order", "id"),
            },
        ),
        migrations.RenameField(
            model_name="course",
            old_name="content",
            new_name="legacy_content",
        ),
        migrations.AddField(
            model_name="course",
            name="capacity",
            field=models.PositiveIntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Aforo",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="duration_hours",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Duración (horas)",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="end_date",
            field=models.DateField(null=True, verbose_name="Fecha de fin"),
        ),
        migrations.AddField(
            model_name="course",
            name="location",
            field=models.CharField(
                max_length=300, null=True, verbose_name="Ubicación o acceso"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="modality",
            field=models.CharField(
                choices=[
                    ("presencial", "Presencial"),
                    ("online", "Online"),
                    ("mixta", "Mixta"),
                ],
                max_length=12,
                null=True,
                verbose_name="Modalidad",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="objectives",
            field=models.TextField(null=True, verbose_name="Objetivos"),
        ),
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Precio",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="requirements",
            field=models.TextField(null=True, verbose_name="Requisitos"),
        ),
        migrations.AddField(
            model_name="course",
            name="start_date",
            field=models.DateField(null=True, verbose_name="Fecha de inicio"),
        ),
        migrations.AlterField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[
                    ("borrador", "Borrador"),
                    ("revision", "En revisión"),
                    ("publicado", "Publicado"),
                    ("inscripcion_cerrada", "Inscripción cerrada"),
                    ("desarrollo", "En desarrollo"),
                    ("finalizado", "Finalizado"),
                    ("cerrado", "Cerrado"),
                    ("cancelado", "Cancelado"),
                ],
                default="borrador",
                max_length=20,
                verbose_name="Estado de publicación",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(max_length=150, verbose_name="Título"),
        ),
        migrations.AddField(
            model_name="course",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="courses",
                to="api.coursecategory",
                verbose_name="Categoría",
            ),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.CheckConstraint(
                check=models.Q(("duration_hours__gt", 0)),
                name="course_duration_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.CheckConstraint(
                check=models.Q(("capacity__gt", 0)), name="course_capacity_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.CheckConstraint(
                check=models.Q(("price__gte", 0)), name="course_price_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.CheckConstraint(
                check=models.Q(("end_date__gte", models.F("start_date"))),
                name="course_dates_ordered",
            ),
        ),
        migrations.AddField(
            model_name="courselesson",
            name="content",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="course_lessons",
                to="api.content",
                verbose_name="Contenido",
            ),
        ),
        migrations.AddField(
            model_name="courselesson",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="api.course",
                verbose_name="Curso",
            ),
        ),
        migrations.AddConstraint(
            model_name="courselesson",
            constraint=models.UniqueConstraint(
                fields=("course", "order"), name="unique_course_lesson_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="courselesson",
            constraint=models.CheckConstraint(
                check=models.Q(("order__gt", 0)), name="course_lesson_order_positive"
            ),
        ),
        migrations.RunPython(migrate_course_data, migrations.RunPython.noop),
        migrations.RemoveField(model_name="course", name="legacy_content"),
    ]
