# Generated by Django 5.0.6 on 2026-07-30 07:27

import api.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_coursecategory_courselesson_remove_course_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="capacity",
            field=models.PositiveIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Aforo",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="category",
            field=models.ForeignKey(
                default=api.models.get_default_course_category,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="courses",
                to="api.coursecategory",
                verbose_name="Categoría",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="duration_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Duración (horas)",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="end_date",
            field=models.DateField(
                default=django.utils.timezone.localdate, verbose_name="Fecha de fin"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="location",
            field=models.CharField(
                default="Pendiente de actualizar",
                max_length=300,
                verbose_name="Ubicación o acceso",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="modality",
            field=models.CharField(
                choices=[
                    ("presencial", "Presencial"),
                    ("online", "Online"),
                    ("mixta", "Mixta"),
                ],
                default="presencial",
                max_length=12,
                verbose_name="Modalidad",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="objectives",
            field=models.TextField(
                default="Pendiente de actualizar", verbose_name="Objetivos"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Precio",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="requirements",
            field=models.TextField(default="Sin requisitos", verbose_name="Requisitos"),
        ),
        migrations.AlterField(
            model_name="course",
            name="start_date",
            field=models.DateField(
                default=django.utils.timezone.localdate, verbose_name="Fecha de inicio"
            ),
        ),
    ]
