# Generated by Django 5.0.6 on 2026-07-30 07:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_course_capacity_alter_course_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseApprovalRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "minimum_attendance_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Asistencia mínima (%)",
                    ),
                ),
                (
                    "minimum_grade",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("10")),
                        ],
                        verbose_name="Calificación mínima",
                    ),
                ),
                (
                    "require_content_completion",
                    models.BooleanField(
                        default=False, verbose_name="Exigir todos los contenidos"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_rule",
                        to="api.course",
                        verbose_name="Curso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regla de aprobación",
                "verbose_name_plural": "Reglas de aprobación",
            },
        ),
        migrations.CreateModel(
            name="CourseCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[("aprobado", "Aprobado"), ("suspenso", "Suspenso")],
                        max_length=10,
                        verbose_name="Resultado",
                    ),
                ),
                (
                    "failure_reasons",
                    models.JSONField(blank=True, default=list, verbose_name="Motivos"),
                ),
                (
                    "attendance_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "final_grade",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "content_completion_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("rule_snapshot", models.JSONField(verbose_name="Regla aplicada")),
                (
                    "evidence_snapshot",
                    models.JSONField(verbose_name="Evidencias aplicadas"),
                ),
                (
                    "input_fingerprint",
                    models.CharField(max_length=64, verbose_name="Huella de entradas"),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                (
                    "evaluated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="completions",
                        to="api.course",
                        verbose_name="Curso",
                    ),
                ),
                (
                    "registration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completion",
                        to="api.registration",
                        verbose_name="Matrícula",
                    ),
                ),
            ],
            options={
                "verbose_name": "Finalización de curso",
                "verbose_name_plural": "Finalizaciones de curso",
            },
        ),
        migrations.CreateModel(
            name="CompletionEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                (
                    "outcome",
                    models.CharField(
                        choices=[("aprobado", "Aprobado"), ("suspenso", "Suspenso")],
                        max_length=10,
                    ),
                ),
                ("failure_reasons", models.JSONField(blank=True, default=list)),
                ("rule_snapshot", models.JSONField()),
                ("evidence_snapshot", models.JSONField()),
                ("input_fingerprint", models.CharField(max_length=64)),
                (
                    "evaluated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "completion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="api.coursecompletion",
                    ),
                ),
            ],
            options={
                "ordering": ("revision",),
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("issued_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "holder_name",
                    models.CharField(
                        max_length=300, verbose_name="Nombre en el certificado"
                    ),
                ),
                (
                    "course_title",
                    models.CharField(
                        max_length=150, verbose_name="Curso en el certificado"
                    ),
                ),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "revocation_reason",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "completion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certificate",
                        to="api.coursecompletion",
                        verbose_name="Finalización",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificado",
                "verbose_name_plural": "Certificados",
            },
        ),
        migrations.CreateModel(
            name="LessonCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Finalizado el"
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration_completions",
                        to="api.courselesson",
                        verbose_name="Lección",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completed_lessons",
                        to="api.registration",
                        verbose_name="Matrícula",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contenido finalizado",
                "verbose_name_plural": "Contenidos finalizados",
            },
        ),
        migrations.AddConstraint(
            model_name="courseapprovalrule",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("minimum_attendance_percentage__isnull", True),
                    ("minimum_attendance_percentage__range", (0, 100)),
                    _connector="OR",
                ),
                name="approval_attendance_between_0_and_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="courseapprovalrule",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("minimum_grade__isnull", True),
                    ("minimum_grade__range", (0, 10)),
                    _connector="OR",
                ),
                name="approval_grade_between_0_and_10",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursecompletion",
            constraint=models.UniqueConstraint(
                fields=("registration", "course"),
                name="unique_completion_registration_course",
            ),
        ),
        migrations.AddConstraint(
            model_name="completionevaluation",
            constraint=models.UniqueConstraint(
                fields=("completion", "revision"),
                name="unique_completion_evaluation_revision",
            ),
        ),
        migrations.AddConstraint(
            model_name="completionevaluation",
            constraint=models.UniqueConstraint(
                fields=("completion", "input_fingerprint"),
                name="unique_completion_evaluation_input",
            ),
        ),
        migrations.AddConstraint(
            model_name="lessoncompletion",
            constraint=models.UniqueConstraint(
                fields=("registration", "lesson"),
                name="unique_registration_lesson_completion",
            ),
        ),
    ]
