"""
Django settings for apialimentaforma project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

from .environment import env, env_bool, env_int, env_json, env_list, load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent.parent
load_dotenv(PROJECT_ROOT / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

ENVIRONMENT = env('APP_ENV', 'development').strip().lower()
if ENVIRONMENT not in {'development', 'test', 'production'}:
    raise ImproperlyConfigured('APP_ENV debe ser development, test o production.')

IS_PRODUCTION = ENVIRONMENT == 'production'
SECRET_KEY = env(
    'SECRET_KEY',
    'clave-efimera-solo-para-desarrollo-no-usar-en-produccion',
    required=IS_PRODUCTION,
)
if IS_PRODUCTION and len(SECRET_KEY) < 50:
    raise ImproperlyConfigured('SECRET_KEY debe tener al menos 50 caracteres en producción.')

DEBUG = env_bool('DEBUG', not IS_PRODUCTION)
if IS_PRODUCTION and DEBUG:
    raise ImproperlyConfigured('DEBUG no puede estar activo en producción.')

ALLOWED_HOSTS = env_list('ALLOWED_HOSTS')
if IS_PRODUCTION and not ALLOWED_HOSTS:
    raise ImproperlyConfigured('ALLOWED_HOSTS es obligatorio en producción.')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    'corsheaders',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'apialimentaforma.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'apialimentaforma.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DB_ENGINE = env('DB_ENGINE', 'django.db.backends.sqlite3')
DATABASES = {
    'default': {
        'ENGINE': DB_ENGINE,
        'NAME': env('DB_NAME', str(BASE_DIR / 'db.sqlite3'), required=IS_PRODUCTION),
        'USER': env('DB_USER', ''),
        'PASSWORD': env(
            'DB_PASSWORD',
            '',
            required=IS_PRODUCTION and DB_ENGINE != 'django.db.backends.sqlite3',
        ),
        'HOST': env('DB_HOST', ''),
        'PORT': env('DB_PORT', ''),
        'CONN_MAX_AGE': env_int('DB_CONN_MAX_AGE', 0),
        'OPTIONS': env_json('DB_OPTIONS'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = env('STATIC_URL', '/static/')
STATIC_ROOT = Path(env('STATIC_ROOT', str(BASE_DIR / 'staticfiles')))
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# La API usa la sesión de Django. Esta opción mantiene la autenticación y el
# cierre de sesión en el servidor y permite proteger las peticiones mutables
# del cliente web mediante CSRF, sin almacenar credenciales en localStorage.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# OpenAPI se genera con drf-spectacular, que mantiene compatibilidad activa con
# las versiones fijadas de Django y DRF. La descripción aclara el requisito CSRF
# que OpenAPI no puede expresar por sí solo para la autenticación de sesión.
SPECTACULAR_SETTINGS = {
    'TITLE': 'Alimenta Forma API',
    'DESCRIPTION': (
        'API REST de Alimenta Forma. La autenticación usa la cookie sessionid de '
        'Django. Las operaciones autenticadas POST, PUT, PATCH y DELETE también '
        'requieren la cookie csrftoken y la cabecera X-CSRFToken con el mismo valor. '
        'Las respuestas 400 contienen errores de validación por campo; 401 indica '
        'que no existe una sesión válida y 403 que la sesión no tiene el permiso '
        'requerido o que la comprobación CSRF ha fallado.'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': r'/api/v1',
}

# Manejo de Imagenes
MEDIA_URL = env('MEDIA_URL', '/media/')
MEDIA_ROOT = Path(env('MEDIA_ROOT', str(BASE_DIR / 'media')))

STORAGES = {
    'default': {
        'BACKEND': env(
            'STORAGE_BACKEND',
            'django.core.files.storage.FileSystemStorage',
        ),
        'OPTIONS': env_json('STORAGE_OPTIONS'),
    },
    'staticfiles': {
        'BACKEND': env(
            'STATIC_STORAGE_BACKEND',
            'django.contrib.staticfiles.storage.StaticFilesStorage',
        ),
        'OPTIONS': env_json('STATIC_STORAGE_OPTIONS'),
    },
}

CORS_ALLOWED_ORIGINS = env_list('CORS_ALLOWED_ORIGINS')
CORS_ALLOW_CREDENTIALS = env_bool('CORS_ALLOW_CREDENTIALS', True)
CSRF_TRUSTED_ORIGINS = env_list('CSRF_TRUSTED_ORIGINS')

# Estas medidas solo se activan en producción para no impedir el desarrollo HTTP local.
if IS_PRODUCTION:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = env_int('SECURE_HSTS_SECONDS', 31536000)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', True)
    SECURE_HSTS_PRELOAD = env_bool('SECURE_HSTS_PRELOAD', True)
    if env_bool('TRUST_X_FORWARDED_PROTO', False):
        SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'
